;; mock-csf-protocol.clar
(impl-trait .conxian-csf-trait.trait-csf-liquidity-v1)
(use-trait sip-010-trait .sip-standards.sip-010-ft-trait)
(define-public (register-liquidity-marker (id (string-ascii 256))) (ok true))
(define-public (execute-csf-swap (in <sip-010-trait>) (out <sip-010-trait>) (amount-in uint) (recipient principal))
  (ok { amount-out: amount-in  fee-collected: (/ amount-in u100) })
)
(define-public (request-flash-liquidity (t <sip-010-trait>) (a uint) (m (buff 32))) (ok true))
(define-public (settle-arbitrage (a <sip-010-trait>) (b <sip-010-trait>) (am uint) (p (list 10 principal))) (ok am))
(define-public (claim-conxian-yield (r <sip-010-trait>) (a uint) (p principal)) (ok a))
(define-public (get-csf-health) (ok { tvl: u1000000  utilization: u50  is-active: true }))
