# Auto-labeler configuration
# See: https://github.com/actions/labeler

enhancement:
- changed-files:
  - any-glob-to-any-file:
    - 'stacks/contracts/**/*.clar'
    - 'stacks/src/**/*.ts'
    - 'scripts/**/*.ts'
    - 'stacks/tests/**/*.ts'

docs:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.md'
    - 'documentation/**'
    - 'README.md'

bugfix:
- changed-files:
  - any-glob-to-any-file:
    - 'stacks/**/*.ts'
    - 'scripts/**/*.sh'
    - '.github/workflows/**'

contracts:
- changed-files:
  - any-glob-to-any-file:
    - 'stacks/contracts/**/*.clar'

security:
- changed-files:
  - any-glob-to-any-file:
    - 'stacks/contracts/**/*.clar'
    - 'documentation/SECURITY.md'
