[project]
name = "conxian-base"
description = "Conxian base manifest: core traits and tokens only"
clarinet_version = "3.5.0"

[accounts]
deployer = { mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw", balance = 100_000_000_000_000 }
wallet_1 = { mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild", balance = 100_000_000_000_000 }
wallet_2 = { mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital", balance = 100_000_000_000_000 }
wallet_3 = { mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high", balance = 100_000_000_000_000 }

# =============================
# Core Traits
# =============================
[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.ft-mintable-trait]
path = "contracts/traits/ft-mintable-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.sip-009-trait]
path = "contracts/traits/sip-009-trait.clar"
clarity_version = 2
epoch = "2.4"

# =============================
# Tokens (SIP-010, SIP-009)
# =============================
[contracts.cxvg-token]
path = "contracts/cxvg-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait"]

[contracts.cxd-token]
path = "contracts/cxd-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait", "ft-mintable-trait"]

[contracts.cxlp-token]
path = "contracts/cxlp-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait", "ft-mintable-trait"]

[contracts.cxtr-token]
path = "contracts/cxtr-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait", "ft-mintable-trait"]

[contracts.cxs-token]
path = "contracts/cxs-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-009-trait"]

# =============================
# Optional: Staking (SIP-010 based)
# =============================
[contracts.cxd-staking]
path = "contracts/cxd-staking.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait"]
