[project]
name = "autovault"
description = "AutoVault DeFi protocol - Phase 1 Consolidated"
requirements = []
clarinet_version = "3.5.0"

[accounts]
deployer = { mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw", balance = 100_000_000_000_000 }
wallet_1 = { mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild", balance = 100_000_000_000_000 }
wallet_2 = { mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital", balance = 100_000_000_000_000 }
wallet_3 = { mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high", balance = 100_000_000_000_000 }

[network]
api_endpoint = "http://localhost:3999"
delay_execution_start = false

[network.testnet]
stacks_node_rpc_address = "https://api.testnet.hiro.so"
bitcoin_node_rpc_address = "https://blockstream.info/testnet/api"

[network.mainnet]
stacks_node_rpc_address = "https://api.hiro.so"
bitcoin_node_rpc_address = "https://blockstream.info/api"

# ===========================================
# TRAITS - Core interfaces
# ===========================================

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.pool-trait]
path = "contracts/traits/pool-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
clarity_version = 2
epoch = "2.4"

# ===========================================
# PHASE 1 CONSOLIDATED CONTRACTS
# ===========================================

# Unified mathematical library consolidating all math functions
[contracts.math-lib-unified]
path = "contracts/math-lib-unified.clar"
clarity_version = 2
epoch = "2.4"

# Consolidated vault system combining best features from all vault contracts
[contracts.vault-core-v2]
path = "contracts/vault-core-v2.clar"
clarity_version = 2
epoch = "2.4"

# Unified DEX factory consolidating all factory contract features
[contracts.dex-factory-unified]
path = "contracts/dex-factory-unified.clar"
clarity_version = 2
epoch = "2.4"

# Supporting contracts for tick math and concentrated liquidity
[contracts.tick-math]
path = "contracts/tick-math.clar"
clarity_version = 2
epoch = "2.4"
