
[contracts.office-manager]
path = "contracts/automation/office-manager.clar"
address = "STSZXAKV7DWTDZN2601WR31BM51BD3YTQXKCF9EZ"
depends_on = [ "rbac" ]

[contracts.agent-treasury]
path = "contracts/agents/agent-treasury.clar"
address = "STSZXAKV7DWTDZN2601WR31BM51BD3YTQXKCF9EZ"
depends_on = [ "office-manager", "automation-traits" ]
