[project]
name = "autovault"
description = "AutoVault DeFi protocol - clarinet config"
requirements = []
clarinet_version = "3.5.0"

[accounts]
deployer = { mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw", balance = 100_000_000_000_000 }
wallet_1 = { mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild", balance = 100_000_000_000_000 }
wallet_2 = { mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital", balance = 100_000_000_000_000 }
wallet_3 = { mnemonic = "cycle puppy glare enroll cost improve round trend wrist mushroom scorpion tower claim oppose clever elephant dinosaur eight problem before frozen dune wagon high", balance = 100_000_000_000_000 }

[network]
api_endpoint = "http://localhost:3999" # clarinet devnet default
delay_execution_start = false

[network.testnet]
stacks_node_rpc_address = "https://api.testnet.hiro.so"
bitcoin_node_rpc_address = "https://blockstream.info/testnet/api"

[network.mainnet]
stacks_node_rpc_address = "https://api.hiro.so"
bitcoin_node_rpc_address = "https://blockstream.info/api"

# ===========================================
# TRAITS - Core interfaces (deploy first)
# ===========================================

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.strategy-trait]
path = "contracts/traits/strategy-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.sip-009-trait]
path = "contracts/traits/sip-009-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.oracle-aggregator-trait]
path = "contracts/traits/oracle-aggregator-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-admin-trait]
path = "contracts/traits/vault-admin-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-trait]
path = "contracts/traits/vault-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-init-trait]
path = "contracts/traits/vault-init-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-production-trait]
path = "contracts/traits/vault-production-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.enhanced-caller-admin-trait]
path = "contracts/traits/enhanced-caller-admin-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.pool-trait]
path = "contracts/traits/pool-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.ownable-trait]
path = "contracts/traits/ownable-trait.clar"
clarity_version = 2
epoch = "2.4"

# ===========================================
# DIMENSIONAL DEFI - Metrics-driven system
# ===========================================

[contracts.dimensional-oracle-trait]
path = "contracts/traits/dimensional-oracle-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dim-registry-trait]
path = "contracts/traits/dim-registry-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dim-registry]
path = "contracts/dimensional/dim-registry.clar"
clarity_version = 2
epoch = "2.4"
depends_on = []

[contracts.dim-graph]
path = "contracts/dimensional/dim-graph.clar"
clarity_version = 2
epoch = "2.4"
depends_on = []

[contracts.dim-metrics]
path = "contracts/dimensional/dim-metrics.clar"
clarity_version = 2
epoch = "2.4"
depends_on = []

[contracts.dim-oracle-automation]
path = "contracts/dimensional/dim-oracle-automation.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["dim-registry", "dimensional-oracle-trait"]

[contracts.dim-yield-stake]
path = "contracts/dimensional/dim-yield-stake.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["dim-metrics", "sip-010-trait"]

[contracts.tokenized-bond]
path = "contracts/dimensional/tokenized-bond.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait"]


# ===========================================
# INFRASTRUCTURE - Core system contracts
# ===========================================

[contracts.math-lib]
path = "contracts/math-lib.clar"
clarity_version = 2
epoch = "2.4"

# Enhanced mathematical libraries for DeFi operations
# [contracts.math-lib-advanced]
# path = "contracts/math-lib-advanced.clar"
# clarity_version = 2
# epoch = "2.4"

# # Enhanced math library with sqrt, pow, ln functions for Phase 3
# [contracts.math-lib-enhanced]
# path = "contracts/math-lib-enhanced.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.fixed-point-math]
# path = "contracts/fixed-point-math.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.precision-calculator]
# path = "contracts/precision-calculator.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.mock-ft]
path = "contracts/mock-ft.clar"
clarity_version = 2
epoch = "2.4"

[contracts.registry]
path = "contracts/registry.clar"
clarity_version = 2
epoch = "2.4"

[contracts.timelock]
path = "contracts/timelock.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.circuit-breaker]
# path = "contracts/circuit-breaker.clar"
# clarity_version = 2
# epoch = "2.4"

# ===========================================
# GOVERNANCE - DAO and governance system
# ===========================================

[contracts.gov-token]
path = "contracts/gov-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dao]
path = "contracts/dao.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.dao-governance]
# path = "contracts/dao-governance.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.dao-automation]
path = "contracts/dao-automation.clar"
clarity_version = 2
epoch = "2.4"

[contracts.enhanced-governance]
path = "contracts/enhanced-governance.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.governance-test-helper]
# path = "contracts/governance-test-helper.clar"
# clarity_version = 2
# epoch = "2.4"

# ===========================================
# VAULT SYSTEM - Core vault functionality
# ===========================================

[contracts.vault-enhanced]
path = "contracts/vault-enhanced.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault]
path = "contracts/vault.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-production]
path = "contracts/vault-production.clar"
clarity_version = 2
epoch = "2.4"

[contracts.treasury]
path = "contracts/treasury.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.enhanced-yield-strategy]
# path = "contracts/enhanced-yield-strategy.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.enhanced-yield-strategy-simple]
# path = "contracts/enhanced-yield-strategy-simple.clar"
# clarity_version = 2
# epoch = "2.4"

## ENABLED: complex yield strategy (experimental)
# [contracts.enhanced-yield-strategy-complex]
# path = "contracts/enhanced-yield-strategy-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.multi-hop-router-v2-complex]
# path = "contracts/multi-hop-router-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.twap-oracle-v2-complex]
# path = "contracts/twap-oracle-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

## Complex variant contracts temporarily excluded due to syntax/semantic errors.
## TODO: Track issue to fix parentheses & unresolved functions before re-adding.
# [contracts.enhanced-yield-strategy-complex]
# path = "contracts/enhanced-yield-strategy-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.multi-hop-router-v2-complex]
# path = "contracts/multi-hop-router-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.twap-oracle-v2-complex]
# path = "contracts/twap-oracle-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

## Complex variant contracts temporarily excluded due to syntax/semantic errors.
## TODO: Track issue to fix parentheses & unresolved functions before re-adding.
# [contracts.enhanced-yield-strategy-complex]
# path = "contracts/enhanced-yield-strategy-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.multi-hop-router-v2-complex]
# path = "contracts/multi-hop-router-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.twap-oracle-v2-complex]
# path = "contracts/twap-oracle-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# ===========================================
# TOKENS - Protocol tokens
# ===========================================

[contracts.cxvg-token]
path = "contracts/cxvg-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.avlp-token]
path = "contracts/avlp-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.creator-token]
path = "contracts/creator-token.clar"
clarity_version = 2
epoch = "2.4"

# ===========================================
# DEX ECOSYSTEM - AMM and liquidity pools
# ===========================================

# [contracts.dex-factory-enhanced]
# path = "contracts/dex-factory-enhanced.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.dex-factory]
# path = "contracts/dex-factory.clar"
# clarity_version = 2
# epoch = "2.4"

# Enhanced DEX Factory V2 with multi-pool type support
# [contracts.dex-factory-v2]
# path = "contracts/dex-factory-v2.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.dex-pool]
path = "contracts/dex-pool.clar"
clarity_version = 2
epoch = "2.4"

[contracts.stable-pool]
path = "contracts/stable-pool.clar"
clarity_version = 2
epoch = "2.4"

[contracts.stable-pool-clean]
path = "contracts/stable-pool-clean.clar"
clarity_version = 2
epoch = "2.4"

# Enhanced stable pool with Curve-style StableSwap invariant
# [contracts.stable-pool-enhanced]
# path = "contracts/stable-pool-enhanced.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.weighted-pool]
path = "contracts/weighted-pool.clar"
clarity_version = 2
epoch = "2.4"

# Concentrated liquidity system (Uniswap V3 style)
# [contracts.concentrated-liquidity-pool]
# path = "contracts/concentrated-liquidity-pool.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.concentrated-swap-logic]
# path = "contracts/concentrated-swap-logic.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.tick-math]
# path = "contracts/tick-math.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.position-nft]
# path = "contracts/position-nft.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.pool-factory]
path = "contracts/pool-factory.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.dex-router]
# path = "contracts/dex-router.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.multi-hop-router]
# path = "contracts/multi-hop-router.clar"
# clarity_version = 2
# epoch = "2.4"

# # [contracts.multi-hop-router-v2]
# # path = "contracts/multi-hop-router-v2.clar"
# # clarity_version = 2
# # epoch = "2.4"

# # [contracts.multi-hop-router-v2-simple]
# # path = "contracts/multi-hop-router-v2-simple.clar"
# # clarity_version = 2
# # epoch = "2.4"

# # ## ENABLED: multi-hop router v2 complex (experimental)
# # [contracts.multi-hop-router-v2-complex]
# # path = "contracts/multi-hop-router-v2-complex-fixed.clar"
# # clarity_version = 2
# # epoch = "2.4"

# # Advanced Multi-Hop Router V3 with Dijkstra's algorithm
# [contracts.multi-hop-router-v3]
# path = "contracts/multi-hop-router-v3.clar"
# clarity_version = 2
# epoch = "2.4"

  # # Fee tier management system for Phase 3
  # [contracts.fee-tier-manager]
  # path = "contracts/fee-tier-manager.clar"
  # clarity_version = 2
  # epoch = "2.4"

  # Enhanced TWAP oracle with manipulation resistance (disabled: file missing)
  # [contracts.twap-oracle-enhanced]
  # path = "contracts/twap-oracle-enhanced.clar"
  # clarity_version = 2
  # epoch = "2.4"

  # Professional LP tools and analytics for Phase 3 (disabled: file missing)
  # [contracts.professional-lp-tools]
  # path = "contracts/professional-lp-tools.clar"
  # clarity_version = 2
  # epoch = "2.4"

# Institutional APIs and risk management for Phase 3
# [contracts.institutional-apis]
# path = "contracts/institutional-apis.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.mock-dex]
path = "contracts/mock-dex.clar"
clarity_version = 2
epoch = "2.4"

# ===========================================
# ORACLE SYSTEM - Price feeds and TWAP
# ===========================================

# [contracts.oracle-aggregator-enhanced]
# path = "contracts/oracle-aggregator-enhanced.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.oracle-aggregator]
path = "contracts/oracle-aggregator.clar"
clarity_version = 2
epoch = "2.4"

[contracts.twap-oracle-v2]
path = "contracts/twap-oracle-v2.clar"
clarity_version = 2
epoch = "2.4"

[contracts.twap-oracle-v2-simple]
path = "contracts/twap-oracle-v2-simple.clar"
clarity_version = 2
epoch = "2.4"

## ENABLED: advanced TWAP oracle v2 complex (experimental)
# [contracts.twap-oracle-v2-complex]
# path = "contracts/twap-oracle-v2-complex.clar"
# clarity_version = 2
# epoch = "2.4"

# ===========================================
# BOUNTY & ANALYTICS - Monitoring and rewards
# ===========================================

[contracts.enhanced-batch-processing]
path = "contracts/enhanced-batch-processing.clar"
clarity_version = 2
epoch = "2.4"

[contracts.advanced-caching-system]
path = "contracts/advanced-caching-system.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.dynamic-load-distribution]
# path = "contracts/dynamic-load-distribution.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.bounty-system]
path = "contracts/bounty-system.clar"
clarity_version = 2
epoch = "2.4"

# [contracts.automated-bounty-system]
# path = "contracts/automated-bounty-system.clar"
# clarity_version = 2
# epoch = "2.4"

[contracts.analytics]
path = "contracts/analytics.clar"
clarity_version = 2
epoch = "2.4"

[contracts.enterprise-monitoring]
path = "contracts/enterprise-monitoring.clar"
clarity_version = 2
epoch = "2.4"

[contracts.state-anchor]
path = "contracts/state-anchor.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-multi-token]
path = "contracts/vault-multi-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.post-deployment-autonomics]
path = "contracts/post-deployment-autonomics.clar"
clarity_version = 2
epoch = "2.4"

[contracts.enhanced-caller]
path = "contracts/enhanced-caller.clar"
clarity_version = 2
epoch = "2.4"

[contracts.deployment-orchestrator]
path = "contracts/deployment-orchestrator.clar"
clarity_version = 2
epoch = "2.4"

[contracts.autovault-registry]
path = "contracts/autovault-registry.clar"
clarity_version = 2
epoch = "2.4"

# ===========================================
# NAKAMOTO ULTRA-PERFORMANCE - SDK 4.0
# ===========================================

# [contracts.nakamoto-optimized-oracle]
# path = "contracts/nakamoto-optimized-oracle.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.sdk-ultra-performance]
# path = "contracts/sdk-ultra-performance.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.nakamoto-factory-ultra]
# path = "contracts/nakamoto-factory-ultra.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.nakamoto-vault-ultra]
# path = "contracts/nakamoto-vault-ultra.clar"
# clarity_version = 2
# epoch = "2.4"

# ===========================================
# ENHANCED ANALYTICS - Advanced monitoring
# ===========================================

# [contracts.enhanced-analytics]
# path = "contracts/enhanced-analytics.clar"
# clarity_version = 2
# epoch = "2.4"

# # [contracts.enhanced-health-monitoring]
# # path = "contracts/enhanced-health-monitoring.clar"
# # clarity_version = 2
# # epoch = "2.4"

# [contracts.governance-metrics]
# path = "contracts/governance-metrics.clar"
# clarity_version = 2
# epoch = "2.4"

# [contracts.reputation-token]
# path = "contracts/reputation-token.clar"
# clarity_version = 2
# epoch = "2.4"
