[project]
name = "conxian-tokens"
description = "Token-only configuration for testing core tokens without enhanced features"
clarinet_version = "3.5.0"

[accounts]
deployer = { mnemonic = "twice kind fence tip hidden tilt action fragile skin nothing glory cousin green tomorrow spring wrist shed math olympic multiply hip blue scout claw", balance = 100_000_000_000_000 }
wallet_1 = { mnemonic = "sell invite acquire kitten bamboo drastic jelly vivid peace spawn twice guilt pave pen trash pretty park cube fragile unaware remain midnight betray rebuild", balance = 100_000_000_000_000 }
wallet_2 = { mnemonic = "hold excess usual excess ring elephant install account glad dry fragile donkey gaze humble truck breeze nation gasp vacuum limb head keep delay hospital", balance = 100_000_000_000_000 }

# Core traits required for tokens
[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.ft-mintable-trait]
path = "contracts/traits/ft-mintable-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.sip-009-trait]
path = "contracts/traits/sip-009-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.monitor-trait]
path = "contracts/traits/monitor-trait.clar"
clarity_version = 2
epoch = "2.4"

# Core token contracts (basic tokens only - no system integration)
[contracts.cxlp-token]
path = "contracts/cxlp-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-010-trait", "ft-mintable-trait"]

[contracts.cxs-token]
path = "contracts/cxs-token.clar"
clarity_version = 2
epoch = "2.4"
depends_on = ["sip-009-trait"]

# Note: Excluded tokens due to system integration hooks:
# - cxd-token: calls protocol-invariant-monitor
# - cxvg-token: has system integration with writing operations in read-only
# - cxtr-token: uses monitor-contract trait with system checks
