-- New table for external settlement logs
-- Requirement: record external_tx_reference, settlement_network_origin, and fiat_value_pegged.
-- Requirement: Link each record to the corresponding native transaction hash.
-- Target Schema: cnx_bos

CREATE TABLE IF NOT EXISTS cnx_bos.cxn_external_settlement_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    native_tx_hash TEXT NOT NULL,
    external_tx_reference TEXT NOT NULL,
    settlement_network_origin TEXT NOT NULL,
    fiat_value_pegged NUMERIC(20, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE cnx_bos.cxn_external_settlement_logs
  ALTER COLUMN currency_code SET DEFAULT 'USD',
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN metadata SET DEFAULT '{}'::jsonb,
  ALTER COLUMN currency_code SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN metadata SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'cxn_ext_settlement_origin_ref_uniq'
      AND conrelid = 'cnx_bos.cxn_external_settlement_logs'::regclass
  ) THEN
    IF EXISTS (
      SELECT 1
      FROM (
        SELECT settlement_network_origin, external_tx_reference
        FROM cnx_bos.cxn_external_settlement_logs
        GROUP BY 1, 2
        HAVING COUNT(*) > 1
      ) d
    ) THEN
      RAISE EXCEPTION
        'Cannot add UNIQUE (settlement_network_origin, external_tx_reference): duplicate rows exist';
    END IF;

    ALTER TABLE cnx_bos.cxn_external_settlement_logs
      ADD CONSTRAINT cxn_ext_settlement_origin_ref_uniq
      UNIQUE (settlement_network_origin, external_tx_reference);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ext_settlement_native_hash ON cnx_bos.cxn_external_settlement_logs(native_tx_hash);
