-- New table for external settlement logs
-- Requirement: record external_tx_reference, settlement_network_origin, and fiat_value_pegged.
-- Requirement: Link each record to the corresponding native transaction hash.
-- Target Schema: cnx_bos

CREATE SCHEMA IF NOT EXISTS cnx_bos;

CREATE TABLE IF NOT EXISTS cnx_bos.cxn_external_settlement_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    native_tx_hash TEXT NOT NULL,
    external_tx_reference TEXT NOT NULL,
    settlement_network_origin TEXT NOT NULL,
    fiat_value_pegged NUMERIC(20, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE cnx_bos.cxn_external_settlement_logs
  ALTER COLUMN currency_code SET DEFAULT 'USD',
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN metadata SET DEFAULT '{}'::jsonb,
  ALTER COLUMN currency_code SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN metadata SET NOT NULL;

DO $$
DECLARE
  table_oid oid;
  origin_attnum SMALLINT;
  ref_attnum SMALLINT;
BEGIN
  table_oid := 'cnx_bos.cxn_external_settlement_logs'::regclass;

  SELECT attnum
  INTO origin_attnum
  FROM pg_attribute
  WHERE attrelid = table_oid
    AND attname = 'settlement_network_origin';

  SELECT attnum
  INTO ref_attnum
  FROM pg_attribute
  WHERE attrelid = table_oid
    AND attname = 'external_tx_reference';

  IF NOT EXISTS (
    SELECT 1
    FROM pg_index i
    WHERE i.indrelid = table_oid
      AND i.indisunique
      AND (
        i.indkey = format('%s %s', origin_attnum, ref_attnum)::int2vector
        OR i.indkey = format('%s %s', ref_attnum, origin_attnum)::int2vector
      )
  ) THEN
    IF EXISTS (
      SELECT 1
      FROM (
        SELECT settlement_network_origin, external_tx_reference
        FROM cnx_bos.cxn_external_settlement_logs
        GROUP BY 1, 2
        HAVING COUNT(*) > 1
      ) d
    ) THEN
      RAISE EXCEPTION
        'Cannot enforce uniqueness on (settlement_network_origin, external_tx_reference): duplicate rows exist';
    END IF;

    EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS idx_ext_settlement_origin_ref_uniq ON cnx_bos.cxn_external_settlement_logs (settlement_network_origin, external_tx_reference)';
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ext_settlement_native_hash ON cnx_bos.cxn_external_settlement_logs(native_tx_hash);
