-- New table for external settlement logs
-- Requirement: record external_tx_reference, settlement_network_origin, and fiat_value_pegged.
-- Requirement: Link each record to the corresponding native transaction hash.
-- Target Schema: cnx_bos

CREATE SCHEMA IF NOT EXISTS cnx_bos;

CREATE TABLE IF NOT EXISTS cnx_bos.cxn_external_settlement_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    native_tx_hash TEXT NOT NULL,
    external_tx_reference TEXT NOT NULL,
    settlement_network_origin TEXT NOT NULL,
    fiat_value_pegged NUMERIC(20, 2) NOT NULL,
    currency_code CHAR(3) NOT NULL DEFAULT 'USD',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb
);

ALTER TABLE cnx_bos.cxn_external_settlement_logs
  ALTER COLUMN currency_code SET DEFAULT 'USD',
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN metadata SET DEFAULT '{}'::jsonb,
  ALTER COLUMN currency_code SET NOT NULL,
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN metadata SET NOT NULL;

DO $$
DECLARE
  table_oid oid;
  origin_attnum SMALLINT;
  ref_attnum SMALLINT;
  old_lock_timeout TEXT;
  existing_index_name TEXT;
  existing_index_schema TEXT;
  matching_constraint_names TEXT[];
  matching_index_names TEXT[];
BEGIN
  table_oid := 'cnx_bos.cxn_external_settlement_logs'::regclass;

  SELECT attnum
  INTO origin_attnum
  FROM pg_attribute
  WHERE attrelid = table_oid
    AND attname = 'settlement_network_origin'
    AND NOT attisdropped;

  SELECT attnum
  INTO ref_attnum
  FROM pg_attribute
  WHERE attrelid = table_oid
    AND attname = 'external_tx_reference'
    AND NOT attisdropped;

  IF origin_attnum IS NULL OR ref_attnum IS NULL THEN
    RAISE EXCEPTION
      'Expected columns settlement_network_origin and external_tx_reference to exist on cnx_bos.cxn_external_settlement_logs before enforcing uniqueness';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conrelid = table_oid
      AND conname = 'cxn_ext_settlement_origin_ref_uniq'
      AND contype = 'u'
  ) THEN
    IF EXISTS (
      SELECT 1
      FROM pg_constraint
      WHERE conrelid = table_oid
        AND conname = 'cxn_ext_settlement_origin_ref_uniq'
        AND contype <> 'u'
    ) THEN
      RAISE EXCEPTION
        'Constraint "cxn_ext_settlement_origin_ref_uniq" exists but is not UNIQUE on %',
        table_oid::regclass;
    END IF;

    SELECT array_agg(c.conname ORDER BY c.conname)
    INTO matching_constraint_names
    FROM pg_constraint c
    WHERE c.conrelid = table_oid
      AND c.contype = 'u'
      AND (
        c.conkey = ARRAY[origin_attnum, ref_attnum]
        OR c.conkey = ARRAY[ref_attnum, origin_attnum]
      )
      AND c.conname <> 'cxn_ext_settlement_origin_ref_uniq';

    IF COALESCE(array_length(matching_constraint_names, 1), 0) > 1 THEN
      RAISE EXCEPTION
        'Multiple UNIQUE constraints found on (settlement_network_origin, external_tx_reference): %',
        matching_constraint_names;
    ELSIF array_length(matching_constraint_names, 1) = 1 THEN
      EXECUTE format(
        'ALTER TABLE cnx_bos.cxn_external_settlement_logs RENAME CONSTRAINT %I TO cxn_ext_settlement_origin_ref_uniq',
        matching_constraint_names[1]
      );

      RETURN;
    END IF;

    SELECT array_agg(format('%I.%I', ns.nspname, c.relname) ORDER BY ns.nspname, c.relname)
    INTO matching_index_names
    FROM pg_index i
    JOIN pg_class c ON c.oid = i.indexrelid
    JOIN pg_namespace ns ON ns.oid = c.relnamespace
    LEFT JOIN pg_constraint cst ON cst.conindid = i.indexrelid
    WHERE i.indrelid = table_oid
      AND i.indisunique
      AND i.indisvalid
      AND i.indpred IS NULL
      AND i.indexprs IS NULL
      AND i.indnkeyatts = 2
      AND i.indnatts = 2
      AND NOT i.indisprimary
      AND cst.oid IS NULL
      AND (
        i.indkey = format('%s %s', origin_attnum, ref_attnum)::int2vector
        OR i.indkey = format('%s %s', ref_attnum, origin_attnum)::int2vector
      );

    IF COALESCE(array_length(matching_index_names, 1), 0) > 1 THEN
      RAISE EXCEPTION 'Multiple matching standalone unique indexes found: %', matching_index_names;
    ELSIF array_length(matching_index_names, 1) = 1 THEN
      SELECT ns.nspname, c.relname
      INTO existing_index_schema, existing_index_name
      FROM pg_index i
      JOIN pg_class c ON c.oid = i.indexrelid
      JOIN pg_namespace ns ON ns.oid = c.relnamespace
      LEFT JOIN pg_constraint cst ON cst.conindid = i.indexrelid
      WHERE i.indrelid = table_oid
        AND i.indisunique
        AND i.indisvalid
        AND i.indpred IS NULL
        AND i.indexprs IS NULL
        AND i.indnkeyatts = 2
        AND i.indnatts = 2
        AND NOT i.indisprimary
        AND cst.oid IS NULL
        AND (
          i.indkey = format('%s %s', origin_attnum, ref_attnum)::int2vector
          OR i.indkey = format('%s %s', ref_attnum, origin_attnum)::int2vector
        );
    END IF;

    IF existing_index_name IS NULL THEN
      old_lock_timeout := current_setting('lock_timeout');
      PERFORM set_config('lock_timeout', '5s', true);
      LOCK TABLE cnx_bos.cxn_external_settlement_logs IN SHARE ROW EXCLUSIVE MODE;
      PERFORM set_config('lock_timeout', old_lock_timeout, true);

      IF EXISTS (
        SELECT 1
        FROM (
          SELECT settlement_network_origin, external_tx_reference
          FROM cnx_bos.cxn_external_settlement_logs
          GROUP BY 1, 2
          HAVING COUNT(*) > 1
        ) d
      ) THEN
        RAISE EXCEPTION
          'Cannot enforce uniqueness on (settlement_network_origin, external_tx_reference): duplicate rows exist';
      END IF;

      IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace ns ON ns.oid = c.relnamespace
        JOIN pg_index i ON i.indexrelid = c.oid
        WHERE i.indrelid = table_oid
          AND ns.nspname = 'cnx_bos'
          AND c.relname = 'idx_ext_settlement_origin_ref_uniq'
          AND NOT (
            i.indisunique
            AND i.indisvalid
            AND i.indpred IS NULL
            AND i.indexprs IS NULL
            AND i.indnkeyatts = 2
            AND i.indnatts = 2
            AND (
              i.indkey = format('%s %s', origin_attnum, ref_attnum)::int2vector
              OR i.indkey = format('%s %s', ref_attnum, origin_attnum)::int2vector
            )
          )
      ) THEN
        RAISE EXCEPTION
          'Existing index idx_ext_settlement_origin_ref_uniq does not match expected UNIQUE (settlement_network_origin, external_tx_reference) definition';
      END IF;

      EXECUTE 'CREATE UNIQUE INDEX IF NOT EXISTS idx_ext_settlement_origin_ref_uniq ON cnx_bos.cxn_external_settlement_logs (settlement_network_origin, external_tx_reference)';
      existing_index_name := 'idx_ext_settlement_origin_ref_uniq';
      existing_index_schema := 'cnx_bos';
    END IF;

    EXECUTE format(
      'ALTER TABLE cnx_bos.cxn_external_settlement_logs ADD CONSTRAINT cxn_ext_settlement_origin_ref_uniq UNIQUE USING INDEX %I.%I',
      existing_index_schema,
      existing_index_name
    );
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_ext_settlement_native_hash ON cnx_bos.cxn_external_settlement_logs(native_tx_hash);
