;; conxian-protocol.clar
(define-constant ERR_UNAUTHORIZED (err u1000))
(define-data-var contract-owner principal 'ST1BK6TFDEJ4TBVWH5SHNB6SPNWGY06YZFG9WMM4P)
(define-map modules (string-ascii 50) { contract: principal  active: bool })
(define-read-only (get-protocol-admin) (var-get contract-owner))
(define-public (register-module (name (string-ascii 50)) (contract principal))
  (begin (asserts! (is-eq tx-sender (var-get contract-owner)) ERR_UNAUTHORIZED) (map-set modules name { contract: contract  active: true }) (ok true))
)
(define-public (set-owner (new-owner principal))
  (begin (asserts! (is-eq tx-sender (var-get contract-owner)) ERR_UNAUTHORIZED) (var-set contract-owner new-owner) (ok true))
)
