;; conxian-access.clar
(impl-trait .core-traits.conxian-access-trait)
(define-constant ERR_UNAUTHORIZED u1000)
(define-data-var contract-owner principal 'ST1BK6TFDEJ4TBVWH5SHNB6SPNWGY06YZFG9WMM4P)
(define-map roles { user: principal  role: uint } bool)
(define-public (has-role (user principal) (role-id uint)) (ok (default-to false (map-get? roles { user: user  role: role-id }))))
(define-public (grant-role (user principal) (role-id uint) (message (buff 32)) (signature (buff 64)) (public-key (buff 33)))
  (begin (asserts! (is-eq tx-sender (var-get contract-owner)) (err ERR_UNAUTHORIZED)) (map-set roles { user: user  role: role-id } true) (ok true))
)
(define-public (revoke-role (user principal) (role-id uint) (message (buff 32)) (signature (buff 64)) (public-key (buff 33)))
  (begin (asserts! (is-eq tx-sender (var-get contract-owner)) (err ERR_UNAUTHORIZED)) (map-delete roles { user: user  role: role-id }) (ok true))
)
(define-public (verify-passkey-signature (params {hash: (buff 32)  sig: (buff 64)  key: (buff 33)})) (ok true))
(define-public (initialize (owner principal)) (begin (asserts! (is-eq tx-sender (var-get contract-owner)) (err ERR_UNAUTHORIZED)) (var-set contract-owner owner) (ok true)))
(define-read-only (get-contract-owner) (var-get contract-owner))
