[network]
name = "devnet"

[accounts]
deployer = { address = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM" }
wallet_1 = { address = "ST1SJ3DTE5DN7X54YDH5D64R3BCB6A2AG2ZQ8YPD5" }
wallet_2 = { address = "ST2CY5V39NHDPWSXMW9MDT5W3R0X5Y6K68159ST7" }
wallet_3 = { address = "ST2F4BK4GZ6C6A0MMDE1V9RE6DMP78A9CJC0Q65D" }
