# Devnet.toml
# Configuration for Stacks devnet environment

[network]
name = "devnet"
stacks_node_rpc_url = "https://stacks-node-api.devnet.stacks.co"
bitcoin_node_rpc_url = "http://blockstack-devnet:18443"

[accounts.deployer]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[accounts.wallet_1]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[accounts.wallet_2]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[accounts.wallet_3]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[accounts.wallet_4]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"

[accounts.wallet_5]
mnemonic = "cute bird surprise boring old news cake design aisle helmet choose tree"
