(impl-trait .sip-standards.sip-010-ft-trait)
(impl-trait .sip-standards.ft-mintable-trait)
(define-fungible-token cxvg-token)
(define-public (transfer (a uint) (s principal) (r principal) (m (optional (buff 34)))) (ok true))
(define-read-only (get-name) (ok "Conxian Vanguard               "))
(define-read-only (get-symbol) (ok "CXVG                           "))
(define-read-only (get-decimals) (ok u8))
(define-read-only (get-balance (u principal)) (ok u0))
(define-read-only (get-total-supply) (ok u0))
(define-read-only (get-token-uri) (ok none))
(define-public (mint (a uint) (r principal)) (ok true))
(define-public (burn (a uint) (o principal)) (ok true))
