;; swap-router.clar
(use-trait sip-010-ft-trait .sip-standards.sip-010-ft-trait)
(use-trait csf-liquidity-trait .conxian-csf-trait.trait-csf-liquidity-v1)
(define-constant ERR_INTERNAL (err u500))
(define-public (csf-swap (liquidity-source <csf-liquidity-trait>) (token-in <sip-010-ft-trait>) (token-out <sip-010-ft-trait>) (amount-in uint) (min-amount-out uint))
  (let ((swap-res (try! (contract-call? liquidity-source execute-csf-swap token-in token-out amount-in tx-sender))))
    (begin (asserts! (>= (get amount-out swap-res) min-amount-out) (err u501)) (ok (get amount-out swap-res)))
  )
)
(define-read-only (get-protocol-status) (ok { version: "v1.1.0-Apex" }))
